//! Coaching rule storage — ported from claude-view
//! (https://github.com/tombelieber/claude-view), MIT licensed. See /NOTICE
//! for the full license text and attribution. claude-view's coaching rules
//! are generated by a server-side fluency/insights engine agentflare
//! deliberately doesn't have (see SECURITY.md — local-only, no daemon); what's
//! ported here is the rule *storage* format itself: a markdown file per rule,
//! with a small header and a body, capped at MAX_RULES.
//!
//! Split into three submodules by concern:
//! - `rule` — the `CoachingRule` type and the `coaching-<id>.md` file format (parse/write), private to this module tree.
//! - `store` — CRUD over the rules directory (list/apply/remove), private to this module tree except where re-exported below.
//! - `cli` — presentation glue for `agentflare coaching {list,apply,remove}`.

mod cli;
pub(crate) mod rule;
mod store;

pub use cli::{cli_apply, cli_remove, print_list};
pub use store::{rule_bodies_for_prompt, rule_bodies_for_tool, untriggered_rule_bodies};

// Only reached from hook.rs's SessionStart test (#[cfg(test)]), to seed a
// rule before asserting it appears in the printed message — a plain,
// non-test build has no caller for it.
#[allow(unused_imports)]
pub use store::apply_rule;

#[cfg(test)]
pub(crate) mod test_support {
    use super::rule::RuleTrigger;

    pub(crate) fn trigger(tools: Vec<String>, auto_match: bool) -> RuleTrigger {
        RuleTrigger { tools, auto_match }
    }
}
