use regex::Regex;
use std::collections::HashMap;
use std::sync::LazyLock;

pub const SKILL_REVIEW: &str = include_str!("skill-review.md");
pub const SKILL_AUDIT: &str = include_str!("skill-audit.md");
pub const SKILL_DEBT: &str = include_str!("skill-debt.md");
pub const SKILL_GAIN: &str = include_str!("skill-gain.md");
pub const SKILL_HELP: &str = include_str!("skill-help.md");
pub const SKILL_PLAYBOOK: &str = include_str!("skill-playbook.md");
pub const SKILL_NO_HALLUCINATION: &str = include_str!("skill-no-hallucination.md");

#[must_use]
pub fn get(name: &str) -> Option<&'static str> {
    match name {
        "review" => Some(SKILL_REVIEW),
        "audit" => Some(SKILL_AUDIT),
        "debt" => Some(SKILL_DEBT),
        "gain" => Some(SKILL_GAIN),
        "help" => Some(SKILL_HELP),
        "playbook" => Some(SKILL_PLAYBOOK),
        "no-hallucination" => Some(SKILL_NO_HALLUCINATION),
        _ => None,
    }
}

#[must_use]
pub fn skills_dir() -> std::path::PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join("agentflare")
        .join("flare-code")
        .join("skills")
}

static CUSTOM_SKILLS: LazyLock<HashMap<String, String>> = LazyLock::new(|| {
    let mut map = HashMap::new();
    let dir = skills_dir();
    if let Ok(entries) = std::fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "md")
                && let Some(name) = path.file_stem().and_then(|s| s.to_str())
            {
                // Reserved built-in mode/skill names can't be shadowed by
                // custom files — a user's full.md must not hijack full mode.
                if crate::config::VALID_MODES.contains(&name) {
                    continue;
                }
                if let Ok(body) = std::fs::read_to_string(&path)
                    && !body.is_empty()
                {
                    map.insert(name.to_string(), body);
                }
            }
        }
    }
    map
});

pub fn get_custom(name: &str) -> Option<String> {
    CUSTOM_SKILLS.get(name).cloned()
}

pub fn custom_skill_names() -> Vec<String> {
    let mut names: Vec<String> = CUSTOM_SKILLS.keys().cloned().collect();
    names.sort();
    names
}

pub struct Finding {
    pub line: usize,
    pub tag: String,
    pub problem: String,
    pub replacement: String,
    pub snippet: String,
}

static NOISE_PATTERNS: LazyLock<Regex> = LazyLock::new(|| {
    // Case-insensitive: real headers vary ("Copyright" vs "COPYRIGHT (c)").
    // `--` (SQL-style) covers SPDX too, matching the `//`/`#` branches --
    // the original only recognized `-- Copyright`, silently letting
    // `-- SPDX-License-Identifier: ...` through in SQL files.
    Regex::new(r"(?im)^\s*(//\s*(Copyright|SPDX)|#\s*(Copyright|SPDX)|\-\-\s*(Copyright|SPDX))")
        .unwrap()
});

static GENERATED_MARKERS: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?-i)(@generated|DO\s+NOT\s+EDIT|Code generated by|AUTOMATICALLY GENERATED)")
        .unwrap()
});

#[must_use]
pub fn pre_filter(text: &str) -> String {
    if text
        .lines()
        .take(5)
        .any(|line| GENERATED_MARKERS.is_match(line))
    {
        return String::new();
    }
    text.lines()
        .map(|line| {
            if NOISE_PATTERNS.is_match(line) || GENERATED_MARKERS.is_match(line) {
                ""
            } else {
                line
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[must_use]
pub fn detect_over_engineering(text: &str) -> Vec<Finding> {
    let text = pre_filter(text);
    let mut findings = Vec::new();
    over_engineering_check_internal(&text, &mut findings, 0);
    findings.sort_by_key(|f| f.line);
    findings
}

fn over_engineering_check_internal(text: &str, findings: &mut Vec<Finding>, base_line: usize) {
    let patterns: &[(&str, &str, &str, &[&str])] = &[
        (
            "lodash",
            "stdlib",
            "Use native JS methods: Array.map, Array.filter, Object.keys.",
            &[
                "from \"lodash\"",
                "from 'lodash'",
                "require(\"lodash\")",
                "require('lodash')",
            ],
        ),
        (
            "moment",
            "native",
            "Use Intl.DateTimeFormat, Date.toLocaleDateString, or Temporal.",
            &[
                "from \"moment\"",
                "from 'moment'",
                "require(\"moment\")",
                "require('moment')",
            ],
        ),
        (
            "axios",
            "native",
            "Use native fetch() instead of axios.",
            &[
                "from \"axios\"",
                "from 'axios'",
                "require(\"axios\")",
                "require('axios')",
            ],
        ),
        (
            "JSON.parse(JSON.stringify(",
            "stdlib",
            "Use structuredClone() for deep copy.",
            &["JSON.parse(JSON.stringify("],
        ),
    ];

    for (line_num, line) in text.lines().enumerate() {
        let lower = line.to_lowercase();
        for (_name, tag, replacement, needles) in patterns {
            if needles.iter().any(|n| lower.contains(&n.to_lowercase())) {
                let trimmed = line.trim().to_string();
                if !findings
                    .iter()
                    .any(|f| f.line == base_line + line_num + 1 && f.problem == trimmed)
                {
                    findings.push(Finding {
                        line: base_line + line_num + 1,
                        tag: (*tag).to_string(),
                        problem: trimmed,
                        replacement: (*replacement).to_string(),
                        snippet: line.to_string(),
                    });
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_lodash_import() {
        let findings = detect_over_engineering("import _ from \"lodash\";\nconst x = 1;");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].tag, "stdlib");
        assert!(findings[0].replacement.contains("Array.map"));
    }

    #[test]
    fn detects_moment_import() {
        let findings = detect_over_engineering("import moment from \"moment\";");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].tag, "native");
    }

    #[test]
    fn detects_axios_import() {
        let findings = detect_over_engineering("const axios = require(\"axios\");");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].tag, "native");
    }

    #[test]
    fn detects_deep_clone_antipattern() {
        let findings = detect_over_engineering("const copy = JSON.parse(JSON.stringify(obj));");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].tag, "stdlib");
        assert!(findings[0].replacement.contains("structuredClone"));
    }

    #[test]
    fn clean_code_returns_empty() {
        let findings = detect_over_engineering("const x = 1;\nfn foo() { Ok(()) }");
        assert!(findings.is_empty());
    }

    #[test]
    fn detects_single_quoted_imports() {
        let findings = detect_over_engineering("import lodash from 'lodash';");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].tag, "stdlib");
    }

    #[test]
    fn ignores_non_lodash_underscore_import() {
        let findings = detect_over_engineering("import _ from \"underscore\";");
        assert!(findings.is_empty());
    }

    #[test]
    fn review_skill_includes_noise_pre_filter() {
        assert!(SKILL_REVIEW.contains("Pre-filter (skip before deeper analysis)"));
        assert!(SKILL_REVIEW.contains("Copyright"));
        assert!(SKILL_REVIEW.contains("DO NOT EDIT"));
    }

    #[test]
    fn pre_filter_preserves_import_lines() {
        let result = pre_filter("import foo from \"bar\";\nconst x = 1;");
        assert_eq!(result, "import foo from \"bar\";\nconst x = 1;");
    }

    #[test]
    fn pre_filter_preserves_require_lines() {
        let result = pre_filter("const _ = require(\"lodash\");\nfn main() {}");
        assert_eq!(result, "const _ = require(\"lodash\");\nfn main() {}");
    }

    #[test]
    fn pre_filter_removes_copyright_headers() {
        let result =
            pre_filter("// Copyright 2024 Acme Corp\n// SPDX-License-Identifier: MIT\nfn foo() {}");
        assert_eq!(result, "\n\nfn foo() {}");
    }

    #[test]
    fn pre_filter_removes_sql_style_spdx_header() {
        let result = pre_filter("-- SPDX-License-Identifier: MIT\nSELECT 1;");
        assert_eq!(result, "\nSELECT 1;");
    }

    #[test]
    fn pre_filter_removes_lowercase_copyright_header() {
        let result = pre_filter("// copyright 2024 Acme Corp\nfn foo() {}");
        assert_eq!(result, "\nfn foo() {}");
    }

    #[test]
    fn pre_filter_returns_empty_for_generated_file() {
        let result = pre_filter(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\nfn foo() {}\nfn bar() {}",
        );
        assert!(result.is_empty());
    }

    #[test]
    fn pre_filter_returns_empty_for_at_generated() {
        let result = pre_filter("@generated\nfn foo() {}");
        assert!(result.is_empty());
    }

    #[test]
    fn pre_filter_preserves_non_noise_lines() {
        let result = pre_filter("fn foo() {}\nfn bar() { return 42; }");
        assert_eq!(result, "fn foo() {}\nfn bar() { return 42; }");
    }

    #[test]
    fn pre_filter_removes_hash_copyright() {
        let result = pre_filter("# Copyright 2024\n# SPDX-License-Identifier: MIT\nfn foo() {}");
        assert_eq!(result, "\n\nfn foo() {}");
    }

    #[test]
    fn pre_filter_still_allows_lodash_detection() {
        let findings = detect_over_engineering("import _ from \"lodash\";\nconst x = 1;");
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].tag, "stdlib");
    }
}
