// Coaching rule storage — ported from claude-view
// (https://github.com/tombelieber/claude-view), MIT licensed. See /NOTICE
// for the full license text and attribution. claude-view's coaching rules
// are generated by a server-side fluency/insights engine agentflare
// deliberately doesn't have (see SECURITY.md — local-only, no daemon); what's
// ported here is the rule *storage* format itself: a markdown file per rule,
// with a small header and a body, capped at MAX_RULES.
use std::path::PathBuf;

/// A coaching rule loaded from a `coaching-<id>.md` file.
#[derive(Debug)]
pub struct CoachingRule {
    pub id: String,
    pub title: String,
    pub body: String,
    pub applied_at: String,
}

pub const MAX_RULES: usize = 8;

pub fn rules_dir() -> PathBuf {
    crate::state::state_dir().join("rules")
}

/// Validate a rule id: non-empty, max 10 chars, starts with an ASCII
/// letter, remaining chars ASCII alphanumeric or `-`. Ported from
/// claude-view's `is_valid_pattern_id`.
fn is_valid_rule_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 10
        && id.starts_with(|c: char| c.is_ascii_alphabetic())
        && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
}

/// Parse a single `coaching-<id>.md` file into a `CoachingRule`. Returns
/// `None` if the filename doesn't match the expected pattern, or if a
/// matching file has no valid `# Applied:` header — such files are skipped
/// entirely (not included with blank fields) so one bad file can never take
/// down the whole listing.
fn parse_rule_file(path: &std::path::Path) -> Option<CoachingRule> {
    let content = std::fs::read_to_string(path).ok()?;
    let filename = path.file_stem()?.to_str()?;
    let id = filename.strip_prefix("coaching-")?.to_string();

    let mut title = String::new();
    let mut applied_at = String::new();
    let mut in_header = false;
    let mut header_done = false;
    let mut body_lines = Vec::new();

    for line in content.lines() {
        if line.starts_with("---") && !header_done {
            in_header = !in_header;
            if !in_header {
                header_done = true;
            }
            continue;
        }
        if in_header {
            if let Some(rest) = line.strip_prefix("# Pattern:") {
                if let Some(t) = rest.split_once('\u{2014}').map(|x| x.1) {
                    title = t.trim().to_string();
                }
            } else if let Some(rest) = line.strip_prefix("# Applied:") {
                applied_at = rest.trim().to_string();
            }
        } else if !line.is_empty() {
            body_lines.push(line);
        }
    }

    // Only return a rule if it has a valid # Applied: header (i.e., was
    // written by write_rule_file). Malformed/empty files are skipped.
    if applied_at.is_empty() {
        return None;
    }

    Some(CoachingRule {
        id,
        title,
        body: body_lines.join(" "),
        applied_at,
    })
}

/// List all coaching rules from the rules directory, sorted by id. Returns
/// an empty vec if the directory doesn't exist or can't be read.
pub fn list_rules() -> Vec<CoachingRule> {
    let dir = rules_dir();
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return Vec::new();
    };

    let mut rules: Vec<CoachingRule> = entries
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.file_name()
                .to_str()
                .map(|n| n.starts_with("coaching-") && n.ends_with(".md"))
                .unwrap_or(false)
        })
        .filter_map(|e| parse_rule_file(&e.path()))
        .collect();

    rules.sort_by(|a, b| a.id.cmp(&b.id));
    rules
}

fn write_rule_file(id: &str, title: &str, body: &str) -> std::io::Result<()> {
    std::fs::create_dir_all(rules_dir())?;
    let date = chrono::Local::now().date_naive();
    let content =
        format!("---\n# Pattern: {id} \u{2014} {title}\n# Applied: {date}\n---\n\n{body}\n");
    std::fs::write(rules_dir().join(format!("coaching-{id}.md")), content)
}

/// Create or overwrite a coaching rule file. Enforces `MAX_RULES` only when
/// `id` is new — updating an existing rule's content never counts against
/// the cap.
pub fn apply_rule(id: &str, title: &str, body: &str) -> Result<CoachingRule, String> {
    if !is_valid_rule_id(id) {
        return Err(format!(
            "invalid rule id '{id}': must be 1-10 chars, start with a letter, and contain only letters, digits, or hyphens"
        ));
    }

    let existing = list_rules();
    let is_overwrite = existing.iter().any(|r| r.id == id);
    if !is_overwrite && existing.len() >= MAX_RULES {
        return Err(format!(
            "maximum {MAX_RULES} coaching rules reached — remove one first"
        ));
    }

    write_rule_file(id, title, body).map_err(|e| format!("failed to write rule file: {e}"))?;

    list_rules()
        .into_iter()
        .find(|r| r.id == id)
        .ok_or_else(|| "rule written but could not be re-read".to_string())
}

/// Remove a coaching rule file by id.
pub fn remove_rule(id: &str) -> Result<(), String> {
    if !is_valid_rule_id(id) {
        return Err(format!("invalid rule id '{id}'"));
    }
    let path = rules_dir().join(format!("coaching-{id}.md"));
    if !path.exists() {
        return Err(format!("rule not found: {id}"));
    }
    std::fs::remove_file(&path).map_err(|e| format!("failed to remove rule file: {e}"))
}

/// All active rule bodies, in id order — what `hook session-start` surfaces.
pub fn active_rule_bodies() -> Vec<String> {
    list_rules().into_iter().map(|r| r.body).collect()
}

pub fn print_list() {
    let rules = list_rules();
    if rules.is_empty() {
        println!(
            "No coaching rules configured. Add one with `agentflare coaching apply <id> --title <title> --body <body>`."
        );
        return;
    }
    println!("agentflare coaching rules ({}/{MAX_RULES}):\n", rules.len());
    for r in &rules {
        println!("  {:<10} {}  (applied {})", r.id, r.title, r.applied_at);
        println!("    {}", r.body);
    }
}

pub fn cli_apply(id: &str, title: &str, body: &str) {
    match apply_rule(id, title, body) {
        Ok(rule) => println!("Applied coaching rule '{}': {}", rule.id, rule.title),
        Err(e) => {
            eprintln!("agentflare coaching apply: {e}");
            std::process::exit(1);
        }
    }
}

pub fn cli_remove(id: &str) {
    match remove_rule(id) {
        Ok(()) => println!("Removed coaching rule '{id}'."),
        Err(e) => {
            eprintln!("agentflare coaching remove: {e}");
            std::process::exit(1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::paths::test_support::with_temp_home;

    #[test]
    fn is_valid_rule_id_accepts_short_alpha_start_ids() {
        assert!(is_valid_rule_id("hygiene"));
        assert!(is_valid_rule_id("a"));
        assert!(is_valid_rule_id("model-1"));
    }

    #[test]
    fn is_valid_rule_id_rejects_empty_too_long_numeric_start_or_bad_chars() {
        assert!(!is_valid_rule_id(""));
        assert!(!is_valid_rule_id("waytoolongforanid"));
        assert!(!is_valid_rule_id("1abc"));
        assert!(!is_valid_rule_id("has space"));
        assert!(!is_valid_rule_id("has_underscore"));
    }

    #[test]
    fn list_rules_returns_empty_when_directory_missing() {
        with_temp_home(|| {
            assert!(list_rules().is_empty());
        });
    }

    #[test]
    fn apply_rule_then_list_rules_roundtrips() {
        with_temp_home(|| {
            let applied = apply_rule(
                "hygiene",
                "Close sessions promptly",
                "Wrap up each phase before starting the next.",
            )
            .unwrap();
            assert_eq!(applied.id, "hygiene");
            assert_eq!(applied.title, "Close sessions promptly");
            assert_eq!(applied.body, "Wrap up each phase before starting the next.");

            let rules = list_rules();
            assert_eq!(rules.len(), 1);
            assert_eq!(rules[0].id, "hygiene");
        });
    }

    #[test]
    fn apply_rule_rejects_invalid_id() {
        with_temp_home(|| {
            let err = apply_rule("1bad", "Title", "Body").unwrap_err();
            assert!(err.contains("invalid rule id"));
            assert!(list_rules().is_empty());
        });
    }

    #[test]
    fn apply_rule_enforces_max_rules_for_new_ids() {
        with_temp_home(|| {
            for i in 0..MAX_RULES {
                apply_rule(&format!("r{i}"), "T", "B").unwrap();
            }
            let err = apply_rule("one-more", "T", "B").unwrap_err();
            assert!(err.contains("maximum"));
            assert_eq!(list_rules().len(), MAX_RULES);
        });
    }

    #[test]
    fn apply_rule_allows_overwriting_existing_id_at_capacity() {
        with_temp_home(|| {
            for i in 0..MAX_RULES {
                apply_rule(&format!("r{i}"), "T", "B").unwrap();
            }
            let updated = apply_rule("r0", "New Title", "New Body").unwrap();
            assert_eq!(updated.title, "New Title");
            assert_eq!(list_rules().len(), MAX_RULES);
        });
    }

    #[test]
    fn remove_rule_deletes_existing_file() {
        with_temp_home(|| {
            apply_rule("hygiene", "T", "B").unwrap();
            remove_rule("hygiene").unwrap();
            assert!(list_rules().is_empty());
        });
    }

    #[test]
    fn remove_rule_errors_when_not_found() {
        with_temp_home(|| {
            let err = remove_rule("missing").unwrap_err();
            assert!(err.contains("not found"));
        });
    }

    #[test]
    fn list_rules_skips_malformed_files_without_crashing() {
        with_temp_home(|| {
            std::fs::create_dir_all(rules_dir()).unwrap();
            std::fs::write(rules_dir().join("coaching-broken.md"), "").unwrap();
            apply_rule("good", "T", "B").unwrap();

            let rules = list_rules();
            assert_eq!(
                rules.len(),
                1,
                "malformed file with no # Applied: header is skipped"
            );
            assert_eq!(rules[0].id, "good");
        });
    }

    #[test]
    fn active_rule_bodies_returns_all_bodies_in_id_order() {
        with_temp_home(|| {
            apply_rule("b-rule", "Title B", "Body B").unwrap();
            apply_rule("a-rule", "Title A", "Body A").unwrap();
            assert_eq!(
                active_rule_bodies(),
                vec!["Body A".to_string(), "Body B".to_string()]
            );
        });
    }

    #[test]
    fn apply_rule_body_with_dashes_line_is_not_truncated() {
        with_temp_home(|| {
            let applied = apply_rule("dashes", "Title", "before\n---\nafter").unwrap();
            assert!(
                applied.body.contains("before"),
                "body should contain text before the --- line: {}",
                applied.body
            );
            assert!(
                applied.body.contains("after"),
                "body should contain text after the --- line: {}",
                applied.body
            );

            let rules = list_rules();
            assert_eq!(rules.len(), 1);
            assert!(rules[0].body.contains("before"));
            assert!(rules[0].body.contains("after"));
        });
    }

    #[test]
    fn apply_rule_title_with_em_dash_is_not_truncated() {
        with_temp_home(|| {
            let applied = apply_rule("emdash", "Foo \u{2014} Bar", "Body").unwrap();
            assert_eq!(applied.title, "Foo \u{2014} Bar");

            let rules = list_rules();
            assert_eq!(rules.len(), 1);
            assert_eq!(rules[0].title, "Foo \u{2014} Bar");
        });
    }
}
