mod agent_install;
mod agent_launch;
mod agents;
mod alias;
mod artifacts;
mod atomic_fs;
mod auth;
mod auth_crypt;
mod auth_db;
mod auth_runner;
mod build_time;
mod channels;
mod claims;
mod cli;
mod coaching;
mod compact;
mod components;
mod cost;
mod db;
mod dev_install;
mod dev_vars;
mod errors;
mod gateway_integrations;
mod gateway_secrets;
mod git;
mod github;
mod hook;
mod hook_redirect;
mod init;
mod jsonc;
mod mcp_prompts;
mod mcp_server;
mod memory;
mod mise_install;
mod optimize;
mod paths;
mod pricing;
mod progress;
mod review;
mod rollup;
mod rule_text;
mod shell;
mod state;
mod tool_install;
mod ui;
mod uninstall;
mod update;
mod worktree;

use clap::Parser;

fn main() {
    color_eyre::install().expect("color_eyre::install failed");
    let cli = cli::Cli::parse();
    cli.command.run();
}
