//! Generic leased-claim ledger: a race-safe atomic acquire/heartbeat/
//! release/done lease over a SQLite table, parameterized by table name and
//! key columns so callers with a single-column key (`item_id`) and callers
//! with a composite key (`repo`, `target`) share one implementation.
//!
//! `table`/`key_columns` are always `&'static str` compile-time constants
//! the crate author writes — never runtime/user input — so building SQL
//! with `format!` for identifiers here is safe; only the actual
//! claim/owner/timestamp *values* are real bind parameters.
//!
//! DDL is not generated by this struct — a composite-key table and a
//! single-column-key table have different enough `PRIMARY KEY` shapes that
//! hand-writing each as a migration string is clearer than codegen.

use rusqlite::{Connection, OptionalExtension, ToSql};

pub struct ClaimLedger {
    table: &'static str,
    key_columns: &'static [&'static str],
}

#[derive(Debug, PartialEq, Eq)]
pub enum Acquire {
    /// We now hold the claim (fresh, stolen-stale, or re-taken our own).
    Acquired,
    /// A live claim is held by someone else; `age_secs` since their heartbeat.
    Held { owner: String, age_secs: i64 },
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct Claim {
    pub key: Vec<String>,
    pub owner: String,
    pub status: String,
    pub created_at: i64,
    pub heartbeat_at: i64,
    pub stale: bool,
}

impl ClaimLedger {
    pub const fn new(table: &'static str, key_columns: &'static [&'static str]) -> Self {
        Self { table, key_columns }
    }

    fn where_pred(&self) -> String {
        self.key_columns
            .iter()
            .enumerate()
            .map(|(i, c)| format!("{c} = ?{}", i + 1))
            .collect::<Vec<_>>()
            .join(" AND ")
    }

    fn key_params<'a>(&self, key: &'a [&'a str]) -> Vec<&'a dyn ToSql> {
        assert_eq!(
            key.len(),
            self.key_columns.len(),
            "key arity must match key_columns"
        );
        key.iter().map(|k| k as &dyn ToSql).collect()
    }

    /// Attempts to claim `key`. Atomic: the upsert only overwrites an
    /// existing row that is done, stale (heartbeat < now-ttl), or already
    /// ours — so it can never steal another owner's live claim. `now`/
    /// `ttl_secs` are passed in so the logic is pure and unit-testable
    /// without mocking the clock.
    pub fn acquire(
        &self,
        conn: &Connection,
        key: &[&str],
        owner: &str,
        now: i64,
        ttl_secs: i64,
    ) -> rusqlite::Result<Acquire> {
        assert_eq!(
            key.len(),
            self.key_columns.len(),
            "key arity must match key_columns"
        );
        let stale_before = now - ttl_secs;
        let key_cols = self.key_columns.join(", ");
        let placeholders = (1..=key.len())
            .map(|i| format!("?{i}"))
            .collect::<Vec<_>>()
            .join(", ");
        let owner_p = key.len() + 1;
        let now_p = key.len() + 2;
        let stale_p = key.len() + 3;
        let t = self.table;
        // RETURNING makes the write and the read of its own outcome one atomic
        // statement, so a concurrent release()/done() on another connection can't
        // land between "we wrote" and "we read back what we wrote" and turn our
        // own successful acquire into a misreported Held/NotFound.
        let sql = format!(
            "INSERT INTO {t} ({key_cols}, owner, status, created_at, heartbeat_at)
             VALUES ({placeholders}, ?{owner_p}, 'claimed', ?{now_p}, ?{now_p})
             ON CONFLICT({key_cols}) DO UPDATE SET
                 owner = excluded.owner, status = 'claimed',
                 created_at = excluded.created_at, heartbeat_at = excluded.heartbeat_at
             WHERE {t}.status = 'done' OR {t}.heartbeat_at < ?{stale_p} OR {t}.owner = excluded.owner
             RETURNING owner, heartbeat_at"
        );
        let mut params = self.key_params(key);
        params.push(&owner);
        params.push(&now);
        params.push(&stale_before);
        let written = match conn.query_row(&sql, params.as_slice(), |r| {
            Ok((r.get::<_, String>(0)?, r.get::<_, i64>(1)?))
        }) {
            Ok(row) => Some(row),
            Err(rusqlite::Error::QueryReturnedNoRows) => None,
            Err(e) => return Err(e),
        };

        // None means the WHERE clause rejected our write — someone else holds a
        // live claim. We didn't acquire, so there's nothing of ours a race could
        // corrupt; a plain follow-up read is fine here (only informs the Held
        // owner/age_secs reported back, not our own claim state).
        let (row_owner, heartbeat_at) = match written {
            Some(row) => row,
            None => {
                let select_sql = format!(
                    "SELECT owner, heartbeat_at FROM {t} WHERE {}",
                    self.where_pred()
                );
                let key_params = self.key_params(key);
                conn.query_row(&select_sql, key_params.as_slice(), |r| {
                    Ok((r.get(0)?, r.get(1)?))
                })?
            }
        };

        Ok(if row_owner == owner {
            Acquire::Acquired
        } else {
            Acquire::Held {
                owner: row_owner,
                age_secs: now - heartbeat_at,
            }
        })
    }

    /// Refreshes the lease on a claim we own. Returns false if the claim is
    /// gone or owned by someone else (don't heartbeat what isn't yours).
    pub fn heartbeat(
        &self,
        conn: &Connection,
        key: &[&str],
        owner: &str,
        now: i64,
    ) -> rusqlite::Result<bool> {
        let owner_p = key.len() + 1;
        let now_p = key.len() + 2;
        let sql = format!(
            "UPDATE {t} SET heartbeat_at = ?{now_p} WHERE {pred} AND owner = ?{owner_p}",
            t = self.table,
            pred = self.where_pred()
        );
        let mut params = self.key_params(key);
        params.push(&owner);
        params.push(&now);
        Ok(conn.execute(&sql, params.as_slice())? > 0)
    }

    /// Drops our claim entirely (frees the key). Owner-scoped.
    pub fn release(&self, conn: &Connection, key: &[&str], owner: &str) -> rusqlite::Result<bool> {
        let owner_p = key.len() + 1;
        let sql = format!(
            "DELETE FROM {t} WHERE {pred} AND owner = ?{owner_p}",
            t = self.table,
            pred = self.where_pred()
        );
        let mut params = self.key_params(key);
        params.push(&owner);
        Ok(conn.execute(&sql, params.as_slice())? > 0)
    }

    /// Ownership check without mutation — used by the `mark_completed` +
    /// deferred-release split to verify the caller still holds the claim
    /// before advancing the item's state.
    pub fn is_owner(&self, conn: &Connection, key: &[&str], owner: &str) -> rusqlite::Result<bool> {
        let sql = format!(
            "SELECT 1 FROM {t} WHERE {pred} AND owner = ?{owner_p} AND status = 'claimed'",
            t = self.table,
            pred = self.where_pred(),
            owner_p = key.len() + 1
        );
        let mut params = self.key_params(key);
        params.push(&owner);
        Ok(conn
            .query_row(&sql, params.as_slice(), |_| Ok(()))
            .optional()?
            .is_some())
    }

    /// Marks our claim done (kept for audit; a done key is re-acquirable).
    pub fn done(
        &self,
        conn: &Connection,
        key: &[&str],
        owner: &str,
        now: i64,
    ) -> rusqlite::Result<bool> {
        let owner_p = key.len() + 1;
        let now_p = key.len() + 2;
        let sql = format!(
            "UPDATE {t} SET status = 'done', heartbeat_at = ?{now_p} WHERE {pred} AND owner = ?{owner_p}",
            t = self.table,
            pred = self.where_pred()
        );
        let mut params = self.key_params(key);
        params.push(&owner);
        params.push(&now);
        Ok(conn.execute(&sql, params.as_slice())? > 0)
    }

    /// Lists every claim in the table. With `include_stale = false`, only
    /// live `claimed` rows are returned — stale or done claims count as
    /// available and are hidden. No scoping beyond the table itself —
    /// callers that need to filter by a leading key column (e.g. "repo")
    /// do so client-side over the returned `key` field.
    pub fn list(
        &self,
        conn: &Connection,
        include_stale: bool,
        now: i64,
        ttl_secs: i64,
    ) -> rusqlite::Result<Vec<Claim>> {
        let stale_before = now - ttl_secs;
        let n = self.key_columns.len();
        let key_cols = self.key_columns.join(", ");
        let sql = format!(
            "SELECT {key_cols}, owner, status, created_at, heartbeat_at FROM {t} ORDER BY {key_cols}",
            t = self.table
        );
        let mut stmt = conn.prepare(&sql)?;
        let rows = stmt.query_map([], |r| {
            let mut key = Vec::with_capacity(n);
            for i in 0..n {
                key.push(r.get::<_, String>(i)?);
            }
            let status: String = r.get(n + 1)?;
            let heartbeat_at: i64 = r.get(n + 3)?;
            Ok(Claim {
                key,
                owner: r.get(n)?,
                stale: status == "claimed" && heartbeat_at < stale_before,
                status,
                created_at: r.get(n + 2)?,
                heartbeat_at,
            })
        })?;
        let all: Vec<Claim> = rows.collect::<Result<_, _>>()?;
        Ok(if include_stale {
            all
        } else {
            all.into_iter()
                .filter(|c| c.status == "claimed" && !c.stale)
                .collect()
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TTL: i64 = 1800;

    fn composite_ledger() -> (Connection, ClaimLedger) {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE claims (
                repo         TEXT NOT NULL,
                target       TEXT NOT NULL,
                owner        TEXT NOT NULL,
                status       TEXT NOT NULL,
                created_at   INTEGER NOT NULL,
                heartbeat_at INTEGER NOT NULL,
                PRIMARY KEY (repo, target)
            );",
        )
        .unwrap();
        (conn, ClaimLedger::new("claims", &["repo", "target"]))
    }

    fn single_ledger() -> (Connection, ClaimLedger) {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(
            "CREATE TABLE test_single (
                id           TEXT NOT NULL PRIMARY KEY,
                owner        TEXT NOT NULL,
                status       TEXT NOT NULL,
                created_at   INTEGER NOT NULL,
                heartbeat_at INTEGER NOT NULL
            );",
        )
        .unwrap();
        (conn, ClaimLedger::new("test_single", &["id"]))
    }

    // --- ported verbatim (behaviorally) from src/claims.rs's composite-key tests ---

    #[test]
    fn acquire_free_target_then_held_by_other() {
        let (c, l) = composite_ledger();
        assert_eq!(
            l.acquire(&c, &["o/r", "issue#1"], "a:1", 1000, TTL)
                .unwrap(),
            Acquire::Acquired
        );
        match l
            .acquire(&c, &["o/r", "issue#1"], "b:2", 1001, TTL)
            .unwrap()
        {
            Acquire::Held { owner, .. } => assert_eq!(owner, "a:1"),
            other => panic!("expected Held, got {other:?}"),
        }
    }

    #[test]
    fn reacquiring_own_live_claim_is_idempotent_and_refreshes_heartbeat() {
        let (c, l) = composite_ledger();
        l.acquire(&c, &["o/r", "issue#1"], "a:1", 1000, TTL)
            .unwrap();
        assert_eq!(
            l.acquire(&c, &["o/r", "issue#1"], "a:1", 1500, TTL)
                .unwrap(),
            Acquire::Acquired
        );
        let hb: i64 = c
            .query_row("SELECT heartbeat_at FROM claims", [], |r| r.get(0))
            .unwrap();
        assert_eq!(hb, 1500, "own re-acquire should refresh heartbeat");
    }

    #[test]
    fn stale_claim_is_stealable_but_fresh_one_is_not() {
        let (c, l) = composite_ledger();
        l.acquire(&c, &["o/r", "issue#1"], "a:1", 1000, TTL)
            .unwrap();
        // Well within TTL — cannot steal.
        assert!(matches!(
            l.acquire(&c, &["o/r", "issue#1"], "b:2", 1000 + 100, TTL)
                .unwrap(),
            Acquire::Held { .. }
        ));
        // Past the TTL — steal succeeds and ownership transfers.
        assert_eq!(
            l.acquire(&c, &["o/r", "issue#1"], "b:2", 1000 + TTL + 1, TTL)
                .unwrap(),
            Acquire::Acquired
        );
        let owner: String = c
            .query_row("SELECT owner FROM claims", [], |r| r.get(0))
            .unwrap();
        assert_eq!(owner, "b:2");
    }

    #[test]
    fn done_target_is_reacquirable_by_anyone() {
        let (c, l) = composite_ledger();
        l.acquire(&c, &["o/r", "issue#1"], "a:1", 1000, TTL)
            .unwrap();
        assert!(l.done(&c, &["o/r", "issue#1"], "a:1", 1100).unwrap());
        assert_eq!(
            l.acquire(&c, &["o/r", "issue#1"], "b:2", 1200, TTL)
                .unwrap(),
            Acquire::Acquired
        );
    }

    #[test]
    fn heartbeat_release_done_are_owner_scoped() {
        let (c, l) = composite_ledger();
        l.acquire(&c, &["o/r", "issue#1"], "a:1", 1000, TTL)
            .unwrap();
        assert!(!l.heartbeat(&c, &["o/r", "issue#1"], "b:2", 1100).unwrap());
        assert!(!l.release(&c, &["o/r", "issue#1"], "b:2").unwrap());
        assert!(!l.done(&c, &["o/r", "issue#1"], "b:2", 1100).unwrap());
        assert!(l.heartbeat(&c, &["o/r", "issue#1"], "a:1", 1100).unwrap());
        assert!(l.release(&c, &["o/r", "issue#1"], "a:1").unwrap());
    }

    #[test]
    fn list_hides_stale_and_done_unless_requested() {
        let (c, l) = composite_ledger();
        l.acquire(&c, &["o/r", "issue#1"], "a:1", 1000, TTL)
            .unwrap();
        l.acquire(&c, &["o/r", "issue#2"], "a:1", 1000, TTL)
            .unwrap();
        l.done(&c, &["o/r", "issue#2"], "a:1", 1000).unwrap();
        // At now well past issue#1's TTL, it is stale.
        let now = 1000 + TTL + 5;
        let live = l.list(&c, false, now, TTL).unwrap();
        assert!(live.is_empty(), "stale + done should be hidden: {live:?}");
        let all = l.list(&c, true, now, TTL).unwrap();
        assert_eq!(all.len(), 2);
        assert!(
            all.iter()
                .any(|c| c.key == vec!["o/r", "issue#1"] && c.stale)
        );
    }

    #[test]
    fn list_returns_keys_for_client_side_scoping() {
        let (c, l) = composite_ledger();
        l.acquire(&c, &["o/r1", "issue#1"], "a:1", 1000, TTL)
            .unwrap();
        l.acquire(&c, &["o/r2", "issue#1"], "a:1", 1000, TTL)
            .unwrap();
        let all = l.list(&c, true, 1000, TTL).unwrap();
        assert_eq!(all.len(), 2);
        let r1: Vec<_> = all.iter().filter(|c| c.key[0] == "o/r1").collect();
        assert_eq!(r1.len(), 1);
        assert_eq!(r1[0].key, vec!["o/r1", "issue#1"]);
    }

    // --- single-column key proves the same matrix works with key arity 1 ---

    #[test]
    fn single_column_key_free_then_held_then_stealable() {
        let (c, l) = single_ledger();
        assert_eq!(
            l.acquire(&c, &["item-1"], "a:1", 1000, TTL).unwrap(),
            Acquire::Acquired
        );
        match l.acquire(&c, &["item-1"], "b:2", 1001, TTL).unwrap() {
            Acquire::Held { owner, .. } => assert_eq!(owner, "a:1"),
            other => panic!("expected Held, got {other:?}"),
        }
        assert_eq!(
            l.acquire(&c, &["item-1"], "b:2", 1000 + TTL + 1, TTL)
                .unwrap(),
            Acquire::Acquired
        );
    }

    #[test]
    fn single_column_key_owner_scoping_and_list() {
        let (c, l) = single_ledger();
        l.acquire(&c, &["item-1"], "a:1", 1000, TTL).unwrap();
        assert!(!l.heartbeat(&c, &["item-1"], "b:2", 1100).unwrap());
        assert!(l.heartbeat(&c, &["item-1"], "a:1", 1100).unwrap());
        assert!(l.done(&c, &["item-1"], "a:1", 1200).unwrap());
        let all = l.list(&c, true, 1200, TTL).unwrap();
        assert_eq!(all.len(), 1);
        assert_eq!(all[0].status, "done");
        assert!(l.list(&c, false, 1200, TTL).unwrap().is_empty());
    }
}
