name: security-check

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-audit
      - run: cargo audit
